app:
  name: "yiqing"
  # release 线上 dev 开发
  mod: "release"
  port: 8081
  version: "V0.1.1"
  start_time: "2022-11-19"
  machine_id: 1
auth:
    jwt_expire: 8760
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 100
  max_age: 30
  max_backups: 10
mysql:
#   host: "106.15.65.147"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "yiqing"
  max_open_conns: 200
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100
admin:
  username: "admin"
  password: "123456"


